version: '3'

services:
  app:
    build: ./app
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  mondo:
    image: mongo
       